[package]
name = "prices"
version = "0.1.0"
edition = "2021"
author = "Kyle Dewhurst"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilio = "*"
tokio = { version = "0.2", features = ["macros", "rt-core", "test-util"] }
coingecko = { git = "https://github.com/kyledewy/coingecko-rs" }
isahc = { version = "0.9", default-features = false, features = ["http2", "text-decoding"]}
rust_decimal = "*"
serde_json = "*"
serde = "*"
async-trait = "*"
dialoguer = "*"
anyhow = "*"